config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'requerment', to: 'home#requerment'
  get 'about', to: 'home#about'
  get 'documention', to: 'home#documention'
  get 'services', to: 'home#services'
  
  get 'user_list', to: 'admins#user_list', as: 'user_list'
  get 'contect_list', to: 'admins#contect_list', as: 'contect_list'
  # delete 'users/:id', to: 'admins#user_remove', as: 'user_remove'
  resources :admins do
    member do
      get 'message'
      get 'show_user'
    end
  end
  get 'azure/pricing', to: 'azure#pricing'
  get 'aws/pricing/:service_code', to: 'aws#pricing'
  get 'compare_cloud_services', to: 'cloud_comparison#compare'
  resources :contects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contect.rb
class Contect < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contects , dependent: :destroy      
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  # before_action :find_user, only: [:destroy]

  def user_list
    @users = User.all
  end

  def show_all_users
    @users = User.all
  end

  def show_user
    @user = User.find_by(id: params[:id])
    if @user
      @user
    else
      redirect_to admins_path, alert: "user not found"
    end
  end

  def contect_list
    @contects = User.joins(:contects).distinct
  end

  def message
    @user = User.find_by(id: params[:id])
    if @user
      @messages = @user.contects
    else
      redirect_to admins_path, alert: "User not found"
    end
  end

  def user_remove
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admins_user_list_path, notice: 'User was successfully deleted.'
    else
      redirect_to admins_user_list_path, alert: 'User could not be deleted.'
    end
  end

  private

  def user_parmas
    68
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
    end
end

app/controllers/aws_controller.rb
class AwsController < ApplicationController
    def pricing
        service_code = params[:service_code] # Get the AWS service code from URL params (e.g., EC2, S3, etc.)
        aws_service = AwsPricingService.new
        prices = aws_service.get_prices(service_code)
    
        if prices.present?
          render json: prices, status: :ok
        else
          render json: { error: 'Unable to fetch AWS pricing data' }, status: :bad_request
        end
    end
  end
  

app/controllers/azure_controller.rb
class AzureController < ApplicationController
    def pricing
      azure_service = AzurePricingService.new
      prices = azure_service.get_prices
  
      if prices.present?
        render json: prices, status: :ok 
      else
        render json: { error: 'Unable to fetch Azure pricing data' }, status: :bad_request
      end
    end
  end
  

app/controllers/cloud_comparison_controller.rb
class CloudComparisonController < ApplicationController
    def compare
      aws_service = AwsPricingService.new
      azure_service = AzurePricingService.new
      gcp_service = GcpPricingService.new('YOUR_GCP_API_KEY')
  
      # Fetch cloud service data
      aws_data = aws_service.get_prices('AmazonEC2')
      azure_data = azure_service.get_prices
      gcp_data = gcp_service.get_prices('YOUR_SERVICE_ID')
  
      # Add logic to compare based on your criteria
      @comparison_results = compare_cloud_services(aws_data, azure_data, gcp_data)
    end
  
    private
  
    def compare_cloud_services(aws_data, azure_data, gcp_data)
      # You can compare based on price, performance, availability, etc.
      # For example, comparing the pricing of similar services
      aws_price = extract_price_from_aws(aws_data)
      azure_price = extract_price_from_azure(azure_data)
      gcp_price = extract_price_from_gcp(gcp_data)
  
      {
        aws: aws_price,
        azure: azure_price,
        gcp: gcp_price
      }
    end
  
    def extract_price_from_aws(data)
      # Extract pricing from AWS data (example)
      data['terms']['OnDemand'].first[1]['priceDimensions'].first[1]['pricePerUnit']['USD']
    end
  
    def extract_price_from_azure(data)
      # Extract pricing from Azure data (example)
      data['Items'].first['retailPrice']
    end
  
    def extract_price_from_gcp(data)
      # Extract pricing from GCP data (example)
      data['skus'].first['pricing']['pricingExpression']['tieredRates'].first['unitPrice']['units']
    end
  end
  

app/controllers/contects_controller.rb
class ContectsController < ApplicationController
  before_action :authenticate_user!
  def new
    @contect = Contect.new
  end

  def create
    @contect = current_user.contects.build(contect_params)
    if @contect.save
      flash[:notice] = 'Message sent successfully!'
      redirect_to new_contect_path
    else
      flash.now[:alert] = 'Failed to send message. Please try again.'
      render :send_message
    end
  end

  private
    
  def contect_params
    params.require(:contect).permit(:first_name, :last_name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only:[:requerment , :services]
  def index
  end

  def about
  end


  def services
  end

  def documention
  end

  def requerment
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contects_helper.rb
module ContectsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/contect_list.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<style>

/* USER LIST TABLE */
.user-list tbody td > img {
    position: relative;
	max-width: 50px;
	float: left;
	margin-right: 15px;
}
.user-list tbody td .user-link {
	display: block;
	font-size: 1.25em;
	padding-top: 3px;
	margin-left: 60px;
  text-decoration:none;
}
.table tbody > tr > td {
	font-size: 0.875em;
	vertical-align: middle;
}
.table {
    border-collapse: separate;
    border-spacing:0 16px;
}
.table tbody tr:hover {
    background-color:#EEEDEB; /* Light blue background on hover */
    cursor: pointer; /* Change the cursor to pointer */
    transition: all 0.3s ease; /* Smooth transition for hover effect */
}
</style>


<div class="container">
<table class="table user-list">
  <thead class="text-light bg-dark">
    <tr class="text-light" style="font-family: sans-serif;">
      <th scope="col" class="ml-3">User</th>
      <th scope="col">Latest Message</th>
      <th scope="col">DateTime</th>
      <th scope="col">Status</th>
	  <th scope="col">Open Email</th>
    </tr>
  </thead>
  <tbody class="">
  <% @contects.each do |user| %> 
    <tr data-href="<%= message_admin_path(user.id) %>" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
	  <td>
		<img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" style="width:50px;">
		<a class="user-link"><%= user.name %></a>
		<span class=""><%= user.username%></span>
	  </td>
      <td>
	    <span class="label label-default"><%= user.contects.last.message.truncate_words(7)%></span>
      </td>
      <td>								
	    <%= user.contects.last.created_at.strftime("%B %d, %Y")%>
      </td>
      <td>
		<span class="text-success">Viewed</span>
	  </td>
	  <td class="" style="">
		<%= button_to ' Open In Email', user_session_path(user), method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' } , class:"btn btn-outline-secondary bi bi-envelope-paper"%>
	  </td>
    </tr>
  <% end %>	
  </tbody>
</table>
</div>

<script>
	document.addEventListener("DOMContentLoaded", function() {
  const rows = document.querySelectorAll("tr[data-href]");
  rows.forEach(row => {
    row.addEventListener("click", function() {
      window.location.href = this.dataset.href;
    });
  });
});

</script>

app/views/admins/message.html.erb
<style>
.user-link{
  display: block;
  font-size:23px;
  text-decoration:none;
}
.table {
    border-collapse: separate;
    border-spacing:0 16px;
}
</style>

<div class="container">
<table class="table">
  <thead class="table-dark">
    <tr>
      <td>
        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" style="width:80px; float:left; margin-right:10px;">
		    <a class="text-light user-link"><%= @user.name %></a>
		    <span class=""><%= @user.username%></span>
      </td>
      <td>DateTime</td>
      <td>Open in Email</td>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
    <tr>
      <td>
        <p><%= message.message %></p>
      </td>
      <td>
        <p><%= message.created_at.strftime("%B %d, %Y") %></p>
      </td>
      <td>
        <%= button_to ' Open In Email', user_session_path(@user), method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' } , class:"btn btn-outline-secondary bi bi-envelope-paper"%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
  

app/views/admins/show_user.html.erb
<div class="container mt-3">
  <div class="bg-dark d-flex shadow">
    <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" style="width:150px;">
    <div class="text-light ms-2">
      <p class="fs-2"><%= @user.name %></p>
      <p class=""><%= @user.username%></p>
      <p class=""><%= @user.email%></p>
    </div>
  </div>
  <div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Activities</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Messages</a>
        </li>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
  </div>
</div>

app/views/admins/user_list.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<style>
body{margin-top:20px;}


/* USER LIST TABLE */
.user-list tbody td > img {
    position: relative;
	max-width: 50px;
	float: left;
	margin-right: 15px;
}
.user-list tbody td .user-link {
	display: block;
	font-size: 1.25em;
	padding-top: 3px;
	margin-left: 60px;
  text-decoration:none;
}
.user-list tbody td .user-subhead {
	font-size: 0.875em;
	font-style: italic;
}

/* TABLES */
.table {
    border-collapse: separate;
	border-spacing:0 16px;
}

</style>

<style>

/* USER LIST TABLE
.user-list tbody td > img {
    position: relative;
	max-width: 50px;
	float: left;
	margin-right: 15px;
}
.user-list tbody td .user-link {
	display: block;
	font-size: 1.25em;
	padding-top: 3px;
	margin-left: 60px;
  text-decoration:none;
}
.table tbody > tr > td {
	font-size: 0.875em;
	vertical-align: middle;
} */
.table {
    border-collapse: separate;
    border-spacing:0 16px;
}
.table tbody tr:hover {
    background-color:#EEEDEB; /* Light blue background on hover */
    cursor: pointer; /* Change the cursor to pointer */
    transition: all 0.3s ease; /* Smooth transition for hover effect */
}
</style>


<div class="container">
<table class="table user-list">
  <thead class="text-light bg-dark">
    <tr class="text-light" style="font-family: sans-serif;">
      <th scope="col" class="ml-3">User</th>
      <th scope="col">Created</th>
      <th scope="col">Status</th>
      <th scope="col">Email</th>
	  <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody class="">
  <% @users.each do |user| %> 
    <tr data-href="<%= show_user_admin_path(user.id) %>" style="box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
	  <td>
		<img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" style="width:50px;">
		<a class="user-link"><%= user.name %></a>
		<span class=""><%= user.username%></span>
	  </td>
      <td>
	    <span class="label label-default"><%= user.created_at.strftime("%B %d, %Y")%></span>
      </td>
      <td>								
	    <span class="text-success">Active</span>
      </td>
      <td>
		<a class=""><%= user.email%></a>
	  </td>
	  <td class="" style="">
		<%= button_to ' Remove', user_session_path(user), method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure?' } , class:"btn btn-outline-danger bi bi-trash3"%>
	  </td>
    </tr>
  <% end %>	
  </tbody>
</table>
</div>

<script>
	document.addEventListener("DOMContentLoaded", function() {
  const rows = document.querySelectorAll("tr[data-href]");
  rows.forEach(row => {
    row.addEventListener("click", function() {
      window.location.href = this.dataset.href;
    });
  });
});

</script>

app/views/cloud_comparison/compare.html.erb
<h1>Cloud Services Comparison</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Cloud Service</th>
      <th>Price (USD)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>AWS</td>
      <td><%= @comparison_results[:aws] %></td>
    </tr>
    <tr>
      <td>Azure</td>
      <td><%= @comparison_results[:azure] %></td>
    </tr>
    <tr>
      <td>GCP</td>
      <td><%= @comparison_results[:gcp] %></td>
    </tr>
  </tbody>
</table>

app/views/contects/new.html.erb
<div class="container mt-4">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>
<%= form_with model: @contect, method: :post do |f| %>
<div class="d-flex justify-content-center align-items-center">
    <div class="col-6">
        <div class="text-center h3 contact-h ">CONTACT US</div>
        <div class="shadow rounded p-4 border-top1 mt-4">
            <div class="row g-3 mb-3">
                <div class="col">
                  <%= f.label :first_name, class:"form-label" %><span class="text-danger">*</span>
                  <%= f.text_field :first_name, class: 'form-control' %>   
                </div>
                <div class="col">
                  <%= f.label :last_name , class:"form-label"%><span class="text-danger">*</span>
                  <%= f.text_field :last_name, class: 'form-control' %> 
                </div>
            </div>
            <div class="mb-3">
              <label for="email" class="form-label">Email address<span class="text-danger">*</span></label>
              <%= f.email_field :email, class: 'form-control' %>
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="message" class="form-label">Type your query here<span class="text-danger">*</span></label>
              <%= f.text_area :message, class: 'form-control' , placholder:"Type your query here" %>
              </div>
            <div class="mb-3 text-center d-grid gap-2">
              <%= f.submit "send message" , class:"btn btn-dark text-white"%>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/home/_header.html.erb
<style>
.custom-icon {
    font-size: 23px;
    color: green;
    /* margin-left: 2px; */
 }
</style>
<header>
    <div class="px-3 py-2 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <i class="bi bi-clouds display-6 me-2"></i>
            <b class="display-6">Cloud Market Place</b>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="#" class="nav-link text-secondary">
                <i class="bi bi-house-door custom-icon"></i>
                Home
              </a>
            </li>
            <li class="d-flex">
            <%= link_to about_path, class: "nav-link text-success d-flex align-items-center" do %>
                <i class="bi bi-clipboard-minus custom-icon"></i>
                <span class="ms-1">About</span>
            <% end %>
            </li>
            <li class="d-flex">
            <% if user_signed_in? %>
              <% if current_user.id == 2 %>
                <%= link_to contect_list_path, class: "nav-link text-success d-flex align-items-center" do %>
                    <i class="bi bi-envelope custom-icon"></i>
                    <span class="ms-1">Messages</span>
                  </a>
                <% end %>
              <% else %> 
                <%= link_to new_contect_path, class: "nav-link text-success d-flex align-items-center" do %>
                    <i class="bi bi-envelope custom-icon"></i>
                    <span class="ms-1">Contect</span>
                  </a>
                <% end %> 
              <% end %>
            <% else %>  
                <%= link_to new_contect_path, class: "nav-link text-success d-flex align-items-center" do %>
                    <i class="bi bi-envelope custom-icon"></i>
                    <span class="ms-1">Contect</span>
                  </a>
                <% end %>
            <% end %>  
            </li>
            <% if user_signed_in? %>
              <% if current_user.id == 2%>
                <li class="d-flex">
                  <%= link_to user_list_path, class: "nav-link text-success d-flex align-items-center" do %>
                    <i class="bi bi-person custom-icon"></i>
                    <span class="ms-1">Users</span> 
                  <% end %>  
                </li>
              <% end %>
            <% end %>
            <li class="d-flex">
            <%= link_to documention_path, class: "nav-link text-success d-flex align-items-center" do %>
                <i class="bi bi-file-richtext custom-icon"></i>
                <span class="ms-1">Docs</span> 
            <% end %>  
            </li>
            <li class="d-flex">
            <%= link_to services_path, class: "nav-link text-success d-flex align-items-center" do %>
                <i class="bi bi-gear custom-icon"></i>
                <span class="ms-1">Service</span>  
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
 <div class="container d-flex justify-content-end">            
    <div class="mt-3">
      <% if user_signed_in? %>
        
        <%= button_to 'Log-out', destroy_user_session_path, method: :delete, class:"btn btn btn btn-outline-success" %>
      <% else %>
        <%= link_to 'Login', user_session_path , class:"btn btn-outline-success me-3 pb-1 pt-1" %>
        <%= link_to 'Sign-up', new_user_registration_path, class: "btn btn-outline-success pb-1 pt-1" %>
      <% end %>  
    </div>
</div>

</header>

app/views/home/about.html.erb
<style>
.custom-class{
  width:200px;
}
.cloud-img{
  /* height:250px;
  max-width:300px; */
}
</style>
<!-- about.html.erb -->

<div class="container mt-2">
  <!-- Introduction Section -->
  <section class="text-center mb-4">
    <h1>About Cloud Marketplace</h1>
    <p class="lead">Connecting Businesses with the Best Cloud Solutions</p>
  </section><hr>

  <!-- Our Values Section -->
  <section class="mb-5 mt-4">
    <h2 class="">What We Stand For</h2>
    <div class="d-flex justify-content-between align-items-center">
      <div class="card border-0 shadow-lg" style="max-width:300px;">
        <div class="card-body">
          <h4 class="card-title">Innovation</h4>
          <p class="card-text">We are constantly pushing the boundaries to bring you the latest in cloud technology.</p>
           <%= image_tag asset_path('cloud1.png'), class: 'card-img' %>
        </div>
      </div>
      <div class="card border-0 shadow-lg" style="max-width:300px;">
        <div class="card-body">
          <h4 class="card-title">Customer Focus</h4>
          <p class="card-text">Your success is our success. We are dedicated to providing exceptional service and support.</p>
           <%= image_tag asset_path('cloud2.png'), class: 'card-img' %>
        </div>
      </div>
      <div class="card border-0 shadow-lg" style="max-width:300px;">
        <div class="card-body">
          <h4 class="card-title">Transparency</h4>
          <p class="card-text">We believe in clear communication and honest pricing, with no hidden fees.</p>
           <%= image_tag asset_path('cloud3.png'), class: 'card-img' %>
        </div>
      </div>
    </div>
  </section>

  <!-- Why Choose Us Section -->
  <section class="mb-5">
    <h2>Why Cloud Marketplace?</h2>
    <p>
      Choosing the right cloud solution is critical, and we make it easy for you. Here’s why businesses trust us:
    </p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="card border-0" style="max-width:400px;">
        <div class="card-body"> 
          <%= image_tag asset_path('cloud7.jpeg'), class: 'card-img shadow-lg', style:"height:400px"%>
        </div>
      </div>
      <div class="card border-0 shadow-lg" style="max-width:300px;">
        <div class="card-body">
          <h4 class="card-title">Expert Guidance</h4> 
          <p class="card-text">Our team of experts is here to guide you every step of the way, from selection to implementation.</p>
          <%= image_tag asset_path('cloud5.jpeg'), class: 'card-img cloud-img', style:"" %>
        </div>
      </div>
      <div class="card border-0 shadow-lg" style="max-width:300px;">
        <div class="card-body">
          <h4 class="card-title ">Proven Success</h4>
          <p class="card-text">See what our customers have to say: Proven Success See what our customers have to say</p>
          <%= image_tag asset_path('cloud6.jpeg'), class: 'card-img cloud-img', style:""%>
        </div>
      </div>
    </div>
  </section>

  <!-- Our Future Section -->
  <section class="mb-5">
    <h2>Looking Ahead</h2>
    <p>
      As we continue to grow, our commitment to innovation and customer success remains our top priority.
      We’re excited about the future and look forward to bringing even more advanced cloud solutions to businesses worldwide.
    </p>
  </section>

  <!-- Call to Action Section -->
  <section class="text-center mb-4">
    <h2>Let’s Connect</h2>
    <p>We’d love to hear from you! Whether you have questions, feedback, or just want to learn more, feel free to <%= link_to 'contact us', new_contect_path, class:"text-success" %> or follow us on social media.</p>
  </section>
</div>

<!-- Footer --> 
<div class="container text-center">
  <a>&copy; <%= Time.now.year %> Cloud Marketplace. All rights reserved.</a><br>
  <a class="text-success"><%= link_to 'Privacy Policy', about_path , class:"text-success"%> | <%= link_to 'Terms of Service', about_path, class:"text-success" %></a>
</div>

<div class="container">
        <div class="d-flex mx-auto text-center my-3 shadow rounded py-3">
            <div class="col">
                <i class="bi bi-geo-alt-fill h-color h2"></i>
                <br />
                <span class="h6 mt-3">Headquaters</span>
                <br />
                <span class="text-muted">Indore</span>
            </div>
            <div class="col">
                <i class="bi bi-envelope-fill e-color h2"></i>
                <br />
                <span class='h6 mt-3'>E-Mail</span>
                <br />
                <span class="text-muted">abcd@gmail.com</span>
            </div>
            <div class="col">
                <i class="bi bi-telephone-fill c-color h2"></i>
                <br />
                <span class="h6 mt-3">Phone</span>
                <br />
                <span class="text-muted">+91-987654321</span>
            </div>
        </div>
</div>

app/views/home/documention.html.erb
<h1>Cloud Marketplace Documentation</h1>

<h2>1. Introduction</h2>
<p>Welcome to the Cloud Marketplace, a platform designed to...</p>

<h2>2. Installation Guide</h2>
<p>Follow these steps to install...</p>

<h2>3. Usage Guide</h2>
<p>After logging in, you can access...</p>

<h2>4. API Documentation</h2>
<p>Our API allows you to interact...</p>

<h2>5. Development Guide</h2>
<p>If you're interested in contributing...</p>

<h2>6. Deployment Guide</h2>
<p>Deploying the Cloud Marketplace...</p>

<h2>7. Troubleshooting</h2>
<p>If you encounter issues...</p>

<h2>8. FAQ</h2>
<p>Here are some frequently asked questions...</p>

<h2>9. Contributing</h2>
<p>We welcome contributions...</p>

<h2>10. License</h2>
<p>This project is licensed under...</p>

<h2>11. Contact Information</h2>
<p>For support, please reach out to...</p>

app/views/home/index.html.erb
 <style>
 .header-text{
   font-size: 100px;
   font-family: "Gill Sans", sans-serif;
 }
 .header-sub-text{
   text-align:center;
   font-size: 20px;
   margin-top: 20px;
 }
 .header-btn-coll{
   margin-top: 50px;
 }
 .header-btn-first{
   background-color: #000;
   width: 250px;
   height: 40px;
   border-radius: 5px;
   box-shadow: 0 4px 14px 0 rgb(0 0 0 / 30%);
   display: flex;
   align-items: center;
   justify-content: center;
   margin-right:20px;
 } 
 .header-btn-second{
  width: 250px;
  height: 40px;
  border-radius: 5px;
  box-shadow: 0 4px 14px 0 rgb(0 0 0 / 30%);
 }  
 .add-req{
   text-decoration: none;
 } 
 </style>

  <div class="container">
    <div class="text-center">
      <span class="h1 header-text">Let's Grow your Business</span>
      <div class="header-sub-text">The Platform that suggest you best cloud service provider on the basis of your business <br> requirements so you can choose best CSP provider.</div>
      <div class="header-btn-coll d-flex justify-content-center">
        <div class="header-btn-first">
        <%= link_to "Add Requirements", requerment_path, class:"add-req text-light" %>
        </div>
        <div class="header-btn-second">
        <button class="btn btn-light">Documentation</button>
        </div>
      </div>
    </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloudMarketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>